# Baby mole-rat
[[item]]
id=32365
invmodel=50808
name="Baby mole-rat"
zoom=2256
modelpitch=369
modelroll=1874
offsetx=0
offsety=20
stackable=0
members=true
primarymalemodel=-1
secondarymalemodel=-1
primaryfemalemodel=-1
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","","","","Drop"]
originalcolours=[5388,5392,5268,5272,5276,4558]
replacementcolours=[317,322,326,328,332,-1830]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=0
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=32366
placeholdertemplate=-1
parameters={ clear=true }


# Baby mole-rat (Placeholder)
[[item]]
id=32366
invmodel=0
name="null"
zoom=2000
modelpitch=0
modelroll=0
offsetx=0
offsety=0
stackable=0
members=false
primarymalemodel=-1
secondarymalemodel=-1
primaryfemalemodel=-1
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","","","","Drop"]
originalcolours=[]
replacementcolours=[]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=0
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=32365
placeholdertemplate=14401
parameters={ clear=true }


