# Dark squirrel
[[item]]
id=32281
invmodel=32205
name="Dark squirrel"
zoom=1872
modelpitch=195
modelroll=333
offsetx=0
offsety=0
stackable=0
price=1
members=true
primarymalemodel=-1
secondarymalemodel=-1
primaryfemalemodel=-1
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","","","","Drop"]
originalcolours=[-27376,-27380,3633,3290,3623,4430]
replacementcolours=[24,12,668,24,673,12]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=0
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=32282
placeholdertemplate=-1
parameters={ clear=true }

# Dark Squirrel (Placeholder)
[[item]]
id=32282
invmodel=0
name="null"
zoom=2000
modelpitch=0
modelroll=0
offsetx=0
offsety=0
stackable=0
price=1
members=false
primarymalemodel=-1
secondarymalemodel=-1
primaryfemalemodel=-1
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","","","","Drop"]
originalcolours=[]
replacementcolours=[]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=0
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=32281
placeholdertemplate=14401
parameters={ clear=true }
