# Great blue heron
[[item]]
id=32297
invmodel=50759
name="Great blue heron"
zoom=2256
modelpitch=381
modelroll=1757
offsetx=10
offsety=25
stackable=0
price=1
members=true
primarymalemodel=-1
secondarymalemodel=-1
primaryfemalemodel=-1
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","","","","Drop"]
originalcolours=[]
replacementcolours=[]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=0
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=32298
placeholdertemplate=-1
parameters={ clear=true }


# Great blue heron (Placeholder)
[[item]]
id=32298
invmodel=0
name="null"
zoom=2000
modelpitch=0
modelroll=0
offsetx=0
offsety=0
stackable=0
price=1
members=false
primarymalemodel=-1
secondarymalemodel=-1
primaryfemalemodel=-1
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","","","","Drop"]
originalcolours=[]
replacementcolours=[]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=0
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=32297
placeholdertemplate=14401
parameters={ clear=true }


