package com.zenyte.game.content.magicstorageunit.enums;

import com.zenyte.game.content.magicstorageunit.StorableSetPiece;
import com.zenyte.game.content.magicstorageunit.StorageUnitElement;
import com.zenyte.game.item.ItemId;
import lombok.Getter;

/**
 * @author Kris | 15/09/2020
 * @see <a href="https://www.rune-server.ee/members/kris/">Rune-Server profile</a>
 */
@Getter
public enum StorableOutfits implements StorageUnitElement {
    BLUE_MYSTIC_ROBES(ItemId.MYSTIC_HAT_10601, new StorableSetPiece(ItemId.MYSTIC_HAT, ItemId.MYSTIC_ROBE_TOP, ItemId.MYSTIC_ROBE_BOTTOM, ItemId.MYSTIC_GLOVES, ItemId.MYSTIC_BOOTS)),
    DARK_MYSTIC_ROBES(ItemId.MYSTIC_HAT_DARK_10602, new StorableSetPiece(ItemId.MYSTIC_HAT_DARK, ItemId.MYSTIC_ROBE_TOP_DARK, ItemId.MYSTIC_ROBE_BOTTOM_DARK, ItemId.MYSTIC_GLOVES_DARK, ItemId.MYSTIC_BOOTS_DARK)),
    LIGHT_MYSTIC_ROBES(ItemId.MYSTIC_HAT_LIGHT_10603, new StorableSetPiece(ItemId.MYSTIC_HAT_LIGHT, ItemId.MYSTIC_ROBE_TOP_LIGHT, ItemId.MYSTIC_ROBE_BOTTOM_LIGHT, ItemId.MYSTIC_GLOVES_LIGHT, ItemId.MYSTIC_BOOTS_LIGHT)),
    DUSK_MYSTIC_ROBES(ItemId.MYSTIC_HAT_DUSK, new StorableSetPiece(ItemId.MYSTIC_HAT_DUSK, ItemId.MYSTIC_ROBE_TOP_DUSK, ItemId.MYSTIC_ROBE_BOTTOM_DUSK, ItemId.MYSTIC_GLOVES_DUSK, ItemId.MYSTIC_BOOTS_DUSK)),
    SKELETAL_ROBES(ItemId.SKELETAL_HELM_10604, new StorableSetPiece(ItemId.SKELETAL_HELM, ItemId.SKELETAL_TOP, ItemId.SKELETAL_BOTTOMS, ItemId.SKELETAL_BOOTS, ItemId.SKELETAL_GLOVES)),
    INFINITY_ROBES(ItemId.INFINITY_TOP_10605, new StorableSetPiece(ItemId.INFINITY_HAT, ItemId.INFINITY_TOP, ItemId.INFINITY_BOTTOMS, ItemId.INFINITY_GLOVES, ItemId.INFINITY_BOOTS)),
    SPLITBARK_ROBES(ItemId.SPLITBARK_HELM_10606, new StorableSetPiece(ItemId.SPLITBARK_HELM, ItemId.SPLITBARK_BODY, ItemId.SPLITBARK_LEGS, ItemId.SPLITBARK_GAUNTLETS, ItemId.SPLITBARK_BOOTS)),
    GHOSTLY_ROBES(ItemId.GHOSTLY_BOOTS_10607, new StorableSetPiece(ItemId.GHOSTLY_HOOD, ItemId.GHOSTLY_ROBE, ItemId.GHOSTLY_ROBE_6108, ItemId.GHOSTLY_GLOVES, ItemId.GHOSTLY_BOOTS, ItemId.GHOSTLY_CLOAK)),
    MOONCLAN_ROBES(ItemId.MOONCLAN_HAT_10608, new StorableSetPiece(ItemId.MOONCLAN_HELM, ItemId.MOONCLAN_HAT, ItemId.MOONCLAN_ARMOUR, ItemId.MOONCLAN_SKIRT, ItemId.MOONCLAN_GLOVES, ItemId.MOONCLAN_BOOTS, ItemId.MOONCLAN_CAPE)),
    LUNAR_ROBES(ItemId.LUNAR_HELM_10609, new StorableSetPiece(ItemId.LUNAR_HELM, ItemId.LUNAR_TORSO, ItemId.LUNAR_LEGS, ItemId.LUNAR_GLOVES, ItemId.LUNAR_BOOTS, ItemId.LUNAR_CAPE, ItemId.LUNAR_AMULET, ItemId.LUNAR_RING)),
    GRACEFUL_OUTFIT(ItemId.GRACEFUL_HOOD, new StorableSetPiece(ItemId.GRACEFUL_HOOD, ItemId.GRACEFUL_TOP, ItemId.GRACEFUL_LEGS, ItemId.GRACEFUL_GLOVES, ItemId.GRACEFUL_BOOTS, ItemId.GRACEFUL_CAPE)),
    GRACEFUL_OUTFIT_ARCEUUS(ItemId.GRACEFUL_HOOD_13579, new StorableSetPiece(ItemId.GRACEFUL_HOOD_13579, ItemId.GRACEFUL_TOP_13583, ItemId.GRACEFUL_LEGS_13585, ItemId.GRACEFUL_GLOVES_13587, ItemId.GRACEFUL_BOOTS_13589, ItemId.GRACEFUL_CAPE_13581)),
    GRACEFUL_OUTFIT_HOSIDIUS(ItemId.GRACEFUL_HOOD_13627, new StorableSetPiece(ItemId.GRACEFUL_HOOD_13627, ItemId.GRACEFUL_TOP_13631, ItemId.GRACEFUL_LEGS_13633, ItemId.GRACEFUL_GLOVES_13635, ItemId.GRACEFUL_BOOTS_13637, ItemId.GRACEFUL_CAPE_13629)),
    GRACEFUL_OUTFIT_LOVAKENGJI(ItemId.GRACEFUL_HOOD_13603, new StorableSetPiece(ItemId.GRACEFUL_HOOD_13603, ItemId.GRACEFUL_TOP_13607, ItemId.GRACEFUL_LEGS_13609, ItemId.GRACEFUL_GLOVES_13611, ItemId.GRACEFUL_BOOTS_13613, ItemId.GRACEFUL_CAPE_13605)),
    GRACEFUL_OUTFIT_PISCARILIUS(ItemId.GRACEFUL_HOOD_13591, new StorableSetPiece(ItemId.GRACEFUL_HOOD_13591, ItemId.GRACEFUL_TOP_13595, ItemId.GRACEFUL_LEGS_13597, ItemId.GRACEFUL_GLOVES_13599, ItemId.GRACEFUL_BOOTS_13601, ItemId.GRACEFUL_CAPE_13593)),
    GRACEFUL_OUTFIT_SHAYZIEN(ItemId.GRACEFUL_HOOD_13615, new StorableSetPiece(ItemId.GRACEFUL_HOOD_13615, ItemId.GRACEFUL_TOP_13619, ItemId.GRACEFUL_LEGS_13621, ItemId.GRACEFUL_GLOVES_13623, ItemId.GRACEFUL_BOOTS_13625, ItemId.GRACEFUL_CAPE_13617)),
    GRACEFUL_OUTFIT_KOUREND(ItemId.GRACEFUL_HOOD_13667, new StorableSetPiece(ItemId.GRACEFUL_HOOD_13667, ItemId.GRACEFUL_TOP_13671, ItemId.GRACEFUL_LEGS_13673, ItemId.GRACEFUL_GLOVES_13675, ItemId.GRACEFUL_BOOTS_13677, ItemId.GRACEFUL_CAPE_13669)),
    GRACEFUL_OUTFIT_AGILITY_ARENA(ItemId.GRACEFUL_HOOD_21061, new StorableSetPiece(ItemId.GRACEFUL_HOOD_21061, ItemId.GRACEFUL_TOP_21067, ItemId.GRACEFUL_LEGS_21070, ItemId.GRACEFUL_GLOVES_21073, ItemId.GRACEFUL_BOOTS_21076, ItemId.GRACEFUL_CAPE_21064)),
    BLACK_NAVAL_ATTIRE(ItemId.BLACK_TRICORN_HAT, new StorableSetPiece(ItemId.BLACK_TRICORN_HAT, ItemId.BLACK_NAVAL_SHIRT, ItemId.BLACK_NAVY_SLACKS)),
    BLUE_NAVAL_ATTIRE(ItemId.BLUE_TRICORN_HAT, new StorableSetPiece(ItemId.BLUE_TRICORN_HAT, ItemId.BLUE_NAVAL_SHIRT, ItemId.BLUE_NAVY_SLACKS)),
    BROWN_NAVAL_ATTIRE(ItemId.BROWN_TRICORN_HAT, new StorableSetPiece(ItemId.BROWN_TRICORN_HAT, ItemId.BROWN_NAVAL_SHIRT, ItemId.BROWN_NAVY_SLACKS)),
    GREEN_NAVAL_ATTIRE(ItemId.GREEN_TRICORN_HAT, new StorableSetPiece(ItemId.GREEN_TRICORN_HAT, ItemId.GREEN_NAVAL_SHIRT, ItemId.GREEN_NAVY_SLACKS)),
    GREY_NAVAL_ATTIRE(ItemId.GREY_TRICORN_HAT, new StorableSetPiece(ItemId.GREY_TRICORN_HAT, ItemId.GREY_NAVAL_SHIRT, ItemId.GREY_NAVY_SLACKS)),
    PURPLE_NAVAL_ATTIRE(ItemId.PURPLE_TRICORN_HAT, new StorableSetPiece(ItemId.PURPLE_TRICORN_HAT, ItemId.PURPLE_NAVAL_SHIRT, ItemId.PURPLE_NAVY_SLACKS)),
    RED_NAVAL_ATTIRE(ItemId.RED_TRICORN_HAT, new StorableSetPiece(ItemId.RED_TRICORN_HAT, ItemId.RED_NAVAL_SHIRT, ItemId.RED_NAVY_SLACKS)),
    ELDER_CHAOS_DRUID_ROBES(ItemId.ELDER_CHAOS_HOOD, new StorableSetPiece(ItemId.ELDER_CHAOS_HOOD, ItemId.ELDER_CHAOS_TOP, ItemId.ELDER_CHAOS_ROBE)),
    EVIL_CHICKEN_COSTUME(ItemId.EVIL_CHICKEN_HEAD, new StorableSetPiece(ItemId.EVIL_CHICKEN_HEAD, ItemId.EVIL_CHICKEN_WINGS, ItemId.EVIL_CHICKEN_LEGS, ItemId.EVIL_CHICKEN_FEET)),
    PYROMANCER_OUTFIT(ItemId.PYROMANCER_HOOD, new StorableSetPiece(ItemId.PYROMANCER_HOOD, ItemId.PYROMANCER_GARB, ItemId.PYROMANCER_ROBE, ItemId.PYROMANCER_BOOTS)),
    ORNATE_OUTFIT(ItemId.ORNATE_HELM, new StorableSetPiece(ItemId.ORNATE_HELM, ItemId.ORNATE_TOP, ItemId.ORNATE_LEGS, ItemId.ORNATE_BOOTS, ItemId.ORNATE_GLOVES, ItemId.ORNATE_CAPE)),
    GOLDSMITH_GAUNTLETS(ItemId.GOLDSMITH_GAUNTLETS, new StorableSetPiece(ItemId.GOLDSMITH_GAUNTLETS)),
    ENHANCED_ICE_GLOVES(30030, new StorableSetPiece(30030)),
    GRACEFUL_OUTFIT_BLACK(32122, new StorableSetPiece(32122, 32126, 32128, 32130, 32132, 32124)),
    GRACEFUL_OUTFIT_BROWN(32110, new StorableSetPiece(32110, 32114, 32116, 32118, 32120, 32112))

    ;

    private final int displayItem;
    private final StorableSetPiece[] pieces;

    StorableOutfits(final int displayItem, final StorableSetPiece... pieces) {
        this.displayItem = displayItem;
        this.pieces = pieces;
    }
}
