[[item]]
inherit=22610
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22613
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22616
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22619
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22622
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22625
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22628
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22631
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22634
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22636
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22638
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22641
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22644
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22647
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22650
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22653
grandexchange=true
parameters={clear = true}

[[item]]
inherit=22656
grandexchange=true
parameters={clear = true}

