# Amethyst items
[[item]]
inherit=[21316, 21318, 21320, 21322, 21324, 21332, 21334, 21336, 21338, 21350]
price=120

# Amethyst
[[item]]
inherit=[21347, 21348]
price=3900

# Amethyst javelin heads
[[item]]
inherit=21352
price=1520

# Amethyst Dart Tip
[[item]]
id=31034
inherit=824
name="Amethyst dart tip"
price=200
grandexchange=true
placeholderid=31035
originalcolours=[61]
replacementcolours=[6846]

# Amethyst Dart tip Placeholder
[[item]]
id=31035
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=31034


# Amethyst Dart
[[item]]
id=31036
inherit=811
name="Amethyst dart"
price=400
grandexchange=true
placeholderid=31037
originalcolours=[61]
replacementcolours=[6846]

# Amethyst Dart Placeholder
[[item]]
id=31037
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=31036

[[item]]
inherit=21326
price=490